# Set up

In [1]:
import pandas as pd

# Load data

In [2]:
# Raw data
df = pd.read_excel('./Data/dummy.xlsx', header=0, index_col=0)
df.head()

,responsetime,F1,F2,SC1,SC2,SC3,SC4,SC5,Q1_1s1,Q1_2t1,...,Q8_1s1,Q8_2t1,Q9_1s1,Q9_2t1,Q10_1s1,Q10_2t1,Q11_1s1,Q11_2t1,Q12_1s1,Q12_2t1
MID,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,3.0,0.0,0.0,0.0,text,4.0,答えない,...,5.0,答えない,4.0,答えない,4.0,答えない,4.0,答えない,4.0,答えない
2,15.0,0.0,0.0,1.0,0.0,0.0,0.0,text,5.0,つらい時でもそっとしておいてくれない,...,5.0,答えない,2.0,答えない,6.0,答えない,6.0,答えない,6.0,答えない
3,20.0,0.0,0.0,5.0,0.0,0.0,0.0,text,4.0,全て似合わない,...,4.0,ある方,4.0,不明,4.0,なし,4.0,両方,4.0,両方
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,100.0,0.0,0.0,5.0,0.0,0.0,0.0,text,2.0,プライベートに関与してきたがる,...,5.0,特になし,3.0,発言がチャラいため,2.0,恥ずかしさとかはないと思う,7.0,人のことをあまり考えない,4.0,普通の人

In [3]:
# Rename variables
var_df = pd.read_excel('./Materials/variables.xlsx', header=0, index_col=None)
var_dict = dict(zip(var_df['name1'], var_df['name2']))

df = df.rename(columns=var_dict)
df.head()

,rt,self_sex,self_age,IOS_score,target_likedislike,target_sex,target_age,relationship,self_tolerance_score,self_tolerance_text,...,target_pleasantness_score,target_pleasantness_text,target_responsibility_score,target_responsibility_text,target_carefulness_score,target_carefulness_text,target_activeness_score,target_activeness_text,target_sociability_score,target_sociability_text
MID,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,3.0,0.0,0.0,0.0,text,4.0,答えない,...,5.0,答えない,4.0,答えない,4.0,答えない,4.0,答えない,4.0,答えない
2,15.0,0.0,0.0,1.0,0.0,0.0,0.0,text,5.0,つらい時でもそっとしておいてくれない,...,5.0,答えない,2.0,答えない,6.0,答えない,6.0,答えない,6.0,答えない
3,20.0,0.0,0.0,5.0,0.0,0.0,0.0,text,4.0,全て似合わない,...,4.0,ある方,4.0,不明,4.0,なし,4.0,両方,4.0,両方
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,100.0,0.0,0.0,5.0,0.0,0.0,0.0,text,2.0,プライベートに関与してきたがる,...,5.0,特になし,3.0,発言がチャラいため,2.0,恥ずかしさとかはないと思う,7.0,人のことをあまり考えない,4.0,普通の人

# Data Exclusion
- Participants described bellow will be excluded from the analysis.
	- They indicate their first language is not Japanese.
	- They do not complete any items in the given questionnaire.
	- They spend time less than 1.5 interquartile range (IQR) below the lower quartile (Q1) or more than 1.5 IQR above the upper quartile (Q3) on completing the questionnaire.

In [4]:
# Participants who DID NOT complete ANY items
df = df.dropna(how='all')
df.head()

,rt,self_sex,self_age,IOS_score,target_likedislike,target_sex,target_age,relationship,self_tolerance_score,self_tolerance_text,...,target_pleasantness_score,target_pleasantness_text,target_responsibility_score,target_responsibility_text,target_carefulness_score,target_carefulness_text,target_activeness_score,target_activeness_text,target_sociability_score,target_sociability_text
MID,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,3.0,0.0,0.0,0.0,text,4.0,答えない,...,5.0,答えない,4.0,答えない,4.0,答えない,4.0,答えない,4.0,答えない
2,15.0,0.0,0.0,1.0,0.0,0.0,0.0,text,5.0,つらい時でもそっとしておいてくれない,...,5.0,答えない,2.0,答えない,6.0,答えない,6.0,答えない,6.0,答えない
3,20.0,0.0,0.0,5.0,0.0,0.0,0.0,text,4.0,全て似合わない,...,4.0,ある方,4.0,不明,4.0,なし,4.0,両方,4.0,両方
5,100.0,0.0,0.0,5.0,0.0,0.0,0.0,text,2.0,プライベートに関与してきたがる,...,5.0,特になし,3.0,発言がチャラいため,2.0,恥ずかしさとかはないと思う,7.0,人のことをあまり考えない,4.0,普通の人
6,30.0,0.0,0.0,2.0,0.0,0.0,0.0,text,5.0,答えない,...,4.0,答えない,4.0,答えない,3.0,答えない,4.0,答えない,4.0,答えない

In [5]:
# IQR
q1 = df['rt'].quantile(0.25)
q3 = df['rt'].quantile(0.75)
iqr = q3 - q1

# Participants who spend time less than 1.5 IQR below the lower quatile (Q1)
lower_limit = q1 - 1.5 * iqr
df = df[df['rt'] > lower_limit]

# Participants who spend time more than 1.5 IQR above the upper quatile (Q3)
upper_limit = q3 + 1.5 * iqr
df= df[df['rt'] < upper_limit]

df.head()

,rt,self_sex,self_age,IOS_score,target_likedislike,target_sex,target_age,relationship,self_tolerance_score,self_tolerance_text,...,target_pleasantness_score,target_pleasantness_text,target_responsibility_score,target_responsibility_text,target_carefulness_score,target_carefulness_text,target_activeness_score,target_activeness_text,target_sociability_score,target_sociability_text
MID,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,3.0,0.0,0.0,0.0,text,4.0,答えない,...,5.0,答えない,4.0,答えない,4.0,答えない,4.0,答えない,4.0,答えない
2,15.0,0.0,0.0,1.0,0.0,0.0,0.0,text,5.0,つらい時でもそっとしておいてくれない,...,5.0,答えない,2.0,答えない,6.0,答えない,6.0,答えない,6.0,答えない
3,20.0,0.0,0.0,5.0,0.0,0.0,0.0,text,4.0,全て似合わない,...,4.0,ある方,4.0,不明,4.0,なし,4.0,両方,4.0,両方
6,30.0,0.0,0.0,2.0,0.0,0.0,0.0,text,5.0,答えない,...,4.0,答えない,4.0,答えない,3.0,答えない,4.0,答えない,4.0,答えない
7,22.0,0.0,0.0,4.0,0.0,0.0,0.0,text,5.0,中国出身で、\n日本で働きながら勉強して日本語を覚えた。,...,2.0,仕事を休めなくても頑張る。,3.0,考えるより行動するタイプ。,5.0,人前で手をつながると、少女のように恥ずかしがる。,3.0,思慮深い。,6.0,いつも明るく笑顔。

In [6]:
# When responses to the open-ended questions are “I would not like to answer this question,” they will be excluded from the analysis.
df = df.replace('答えない', '')
df.head()

,rt,self_sex,self_age,IOS_score,target_likedislike,target_sex,target_age,relationship,self_tolerance_score,self_tolerance_text,...,target_pleasantness_score,target_pleasantness_text,target_responsibility_score,target_responsibility_text,target_carefulness_score,target_carefulness_text,target_activeness_score,target_activeness_text,target_sociability_score,target_sociability_text
MID,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,3.0,0.0,0.0,0.0,text,4.0,,...,5.0,,4.0,,4.0,,4.0,,4.0,
2,15.0,0.0,0.0,1.0,0.0,0.0,0.0,text,5.0,つらい時でもそっとしておいてくれない,...,5.0,,2.0,,6.0,,6.0,,6.0,
3,20.0,0.0,0.0,5.0,0.0,0.0,0.0,text,4.0,全て似合わない,...,4.0,ある方,4.0,不明,4.0,なし,4.0,両方,4.0,両方
6,30.0,0.0,0.0,2.0,0.0,0.0,0.0,text,5.0,,...,4.0,,4.0,,3.0,,4.0,,4.0,
7,22.0,0.0,0.0,4.0,0.0,0.0,0.0,text,5.0,中国出身で、\n日本で働きながら勉強して日本語を覚えた。,...,2.0,仕事を休めなくても頑張る。,3.0,考えるより行動するタイプ。,5.0,人前で手をつながると、少女のように恥ずかしがる。,3.0,思慮深い。,6.0,いつも明るく笑顔。

# Output
Save:
- Text data as txt
- Data frame as xlsx

## Text Data

In [7]:
text_vars_self = [
	'self_tolerance_text',
	'self_pleasantness_text',
	'self_responsibility_text',
	'self_carefulness_text',
	'self_activeness_text',
	'self_sociability_text']

text_vars_target = [
	'target_tolerance_text',
	'target_pleasantness_text',
	'target_responsibility_text',
	'target_carefulness_text',
	'target_activeness_text',
	'target_sociability_text']

In [8]:
text_vars_self

['self_tolerance_text',
 'self_pleasantness_text',
 'self_responsibility_text',
 'self_carefulness_text',
 'self_activeness_text',
 'self_sociability_text']

In [9]:
text_vars_target

['target_tolerance_text',
 'target_pleasantness_text',
 'target_responsibility_text',
 'target_carefulness_text',
 'target_activeness_text',
 'target_sociability_text']

In [10]:
print(text_vars_self + text_vars_target)

['self_tolerance_text', 'self_pleasantness_text', 'self_responsibility_text', 'self_carefulness_text', 'self_activeness_text', 'self_sociability_text', 'target_tolerance_text', 'target_pleasantness_text', 'target_responsibility_text', 'target_carefulness_text', 'target_activeness_text', 'target_sociability_text']

In [11]:
text_vars_all =  text_vars_self + text_vars_target
df.loc[:, text_vars_all].head()

,self_tolerance_text,self_pleasantness_text,self_responsibility_text,self_carefulness_text,self_activeness_text,self_sociability_text,target_tolerance_text,target_pleasantness_text,target_responsibility_text,target_carefulness_text,target_activeness_text,target_sociability_text
MID,,,,,,,,,,,,
1,,,,,,,,,,,,
2,つらい時でもそっとしておいてくれない,悪くはない,自分に自信がアルフォルノ,誰とでも話す,,,,,,,,
3,全て似合わない,とにかくあわない,合わない,合う事が無い,鬱陶しい,わからない,どっちでもない,ある方,不明,なし,両方,両方
6,,,,,,,,,,,,
7,中国出身で、\n日本で働きながら勉強して日本語を覚えた。,いつも悩みを聞いてくれる。,自分のことよりも人の心配をする。,飲食店で働き、人当たりが良く人気。,いくつになってもおちゃめ。,人が困っていると、自分のことよりも優先して世話をやく。,飲食店でどのお客にもきさくに接する。,仕事を休めなくても頑張る。,考えるより行動するタイプ。,人前で手をつながると、少女のように恥ずかしがる。,思慮深い。,いつも明るく笑顔。

In [12]:
filename = './Results/output01_all.txt'
with open(filename, 'w') as f:
	df_string = df.loc[:, text_vars_all].to_string(header=False, index=False)
	f.write(df_string)

In [13]:
filename = './Results/output01_self.txt'
with open(filename, 'w') as f:
	df_string = df.loc[:, text_vars_self].to_string(header=False, index=False)
	f.write(df_string)

In [14]:
filename = './Results/output01_target.txt'
with open(filename, 'w') as f:
	df_string = df.loc[:, text_vars_target].to_string(header=False, index=False)
	f.write(df_string)

## Data Frame

In [16]:
df.drop(text_vars_all, axis='columns', inplace=True)
df.head()

,rt,self_sex,self_age,IOS_score,target_likedislike,target_sex,target_age,relationship,self_tolerance_score,self_pleasantness_score,self_responsibility_score,self_carefulness_score,self_activeness_score,self_sociability_score,target_tolerance_score,target_pleasantness_score,target_responsibility_score,target_carefulness_score,target_activeness_score,target_sociability_score
MID,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,3.0,0.0,0.0,0.0,text,4.0,4.0,4.0,4.0,4.0,4.0,5.0,5.0,4.0,4.0,4.0,4.0
2,15.0,0.0,0.0,1.0,0.0,0.0,0.0,text,5.0,5.0,7.0,2.0,4.0,5.0,7.0,5.0,2.0,6.0,6.0,6.0
3,20.0,0.0,0.0,5.0,0.0,0.0,0.0,text,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
6,30.0,0.0,0.0,2.0,0.0,0.0,0.0,text,5.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0
7,22.0,0.0,0.0,4.0,0.0,0.0,0.0,text,5.0,7.0,1.0,1.0,6.0,1.0,7.0,2.0,3.0,5.0,3.0,6.0

In [17]:
filename = './Results/output01_all.csv'
df.to_csv(filename, index=True)