# Setup

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import gensim

In [4]:
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances, manhattan_distances

In [37]:
from ydata_profiling import ProfileReport

# Tokenization
We will focus on specific kinds of part-of-speech (POS), i.e.,
- Adjectives
- Verbs and nouns that form verbs when "suru" is added as a suffix
- nouns

## POS tagging

In [5]:
!mecab -o ./Results/output01_self.txt.mecab ./Results/output01_self.txt
!mecab -o ./Results/output01_target.txt.mecab ./Results/output01_target.txt

## Morphological Analysis

In [6]:
def my_morphol(filename):
	sentences = []
	sentence = []
	previous_line = ''
	MID = -1
	with open(filename, mode='r') as f:
		for line in f:
			# headerに相当する最初の行をスキップ
			# 文頭 or 文中
			if line != 'EOS\n':
				fields = line.split('\t')
				attr = fields[1].split(',')
				# 変数名行
				if previous_line == '':
					continue
				# MID行
				elif fields[0] == 'MID':
					continue
				# 文頭
				elif previous_line == 'EOS\n' and attr[1] == '数':
					MID = int(fields[0])
					sentence.append(MID)
				# 文中
				else:
					morph = {'surface': fields[0], 'base': attr[6], 'pos': attr[0], 'pos1': attr[1]}
					sentence.append(morph)
			# 文末（EOS行）
			else:
				if MID > 0 and len(sentence) > 0:
					sentences.append(sentence)
					sentence = []
					MID = -1
				elif MID > 0 and len(sentence) == 0:
					sentences.append([])
					sentence = []
					MID = -1

			previous_line = line

	return sentences

In [7]:
# SELF
filename = './Results/output01_self.txt.mecab'
sentences_self = my_morphol(filename)

In [8]:
sentences_self[0]

[2,
 {'surface': '.', 'base': '*\n', 'pos': '名詞', 'pos1': 'サ変接続'},
 {'surface': '0', 'base': '*\n', 'pos': '名詞', 'pos1': '数'},
 {'surface': '回答', 'base': '回答', 'pos': '名詞', 'pos1': 'サ変接続'},
 {'surface': '梨', 'base': '梨', 'pos': '名詞', 'pos1': '一般'}]

In [9]:
len(sentences_self)

479

In [10]:
# TARGET
filename = './Results/output01_target.txt.mecab'
sentences_target = my_morphol(filename)

In [11]:
sentences_target[0]

[2,
 {'surface': '.', 'base': '*\n', 'pos': '名詞', 'pos1': 'サ変接続'},
 {'surface': '0', 'base': '*\n', 'pos': '名詞', 'pos1': '数'}]

In [12]:
len(sentences_target)

479

## Tokenization

In [13]:
def my_tokenization(sentences):
	sentences_token = []
#	sentence_token = []
	sentence_token_adj = []
	sentence_token_verb = []
	sentence_token_noun = []

	for sentence in sentences:
		# sentence[0] = MID
#		sentence_token.append(sentence[0])

		for morph in sentence[1:]:
			# POS according to https://www.gavo.t.u-tokyo.ac.jp/~mine/japanese/nlp+slp/NAIST-JDIC_manual.pdf
			# Words for Traits
			if morph['pos'] == '形容詞' and morph['pos1'] == '自立':
				sentence_token_adj.append(morph['base'])
			elif morph['pos'] == '名詞' and morph['pos1'] == '形容動詞語幹':
				if morph['base'] != '*\n':
					sentence_token_adj.append(morph['base'])
			elif morph['pos'] == '名詞' and morph['pos1'] == 'ナイ形容詞語幹':
				if morph['base'] != '*\n':
					sentence_token_adj.append(morph['base'])

			# Words for Behaviors
			elif morph['pos'] == '動詞' and morph['pos1'] == '自立':
				sentence_token_verb.append(morph['base'])
			elif morph['pos'] == '名詞' and morph['pos1'] == 'サ変接続':
				if morph['base'] != '*\n':	# e.g, {'surface': '､', 'base': '*\n', 'pos': '名詞', 'pos1': 'サ変接続'}
					sentence_token_verb.append(morph['base'])

			# Words for Stereotype etc
			elif morph['pos'] == '名詞' and morph['pos1'] == '一般':
				if morph['base'] != '*\n':	# e.g., {'surface': 'キャパオーバー', 'base': '*\n', 'pos': '名詞', 'pos1': '一般'},
					sentence_token_noun.append(morph['base'])
			elif morph['pos'] == '名詞' and morph['pos1'] == '固有名詞':
				if morph['base'] != '*\n':	# {'surface': 'k', 'base': '*\n', 'pos': '名詞', 'pos1': '固有名詞'}
					sentence_token_noun.append(morph['base'])
			elif morph['pos'] == '名詞' and morph['pos1'] == '代名詞':
				if morph['base'] != '*\n':
					sentence_token_noun.append(morph['base'])

		sentences_token.append([sentence[0], sentence_token_adj, sentence_token_verb, sentence_token_noun])
#		sentence_token = []
		sentence_token_adj = []
		sentence_token_verb = []
		sentence_token_noun = []

	return sentences_token

In [14]:
# SELF
sentences_token_self = my_tokenization(sentences_self)
sentences_token_self_df = pd.DataFrame(sentences_token_self, columns=['MID', 'Adj', 'Verb', 'Noun'])
sentences_token_self_df.set_index('MID', inplace=True)
sentences_token_self_df.head()

          Adj                                Verb                      Noun
MID
2          []                                [回答]                       [梨]
5          []                            [見る, 言う]                      [文句]
7    [直ぐ, 慎重]  [許す, 聞く, 仕事, なる, 落とす, 進める, 飲む, 嫌う]  [人, 道, 休暇, 気, たま, 物, 物事]
8          []                                  []                      [かし]
11   [普通, ない]                    [いう, 守る, 排除, する]               [人, 社交, 他者]

In [15]:
# TARGET
sentences_token_target = my_tokenization(sentences_target)
sentences_token_target_df = pd.DataFrame(sentences_token_target, columns=['MID', 'Adj', 'Verb', 'Noun'])
sentences_token_target_df.set_index('MID', inplace=True)
sentences_token_target_df.head()

                              Adj                        Verb      Noun
MID
2                              []                          []        []
5                        [悪い, ない]  [見かける, 見る, 言う, 見る, 許す, 反応]  [愛想, 文句]
7    [直ぐ, 優しい, 真面目, 勤勉, 大人しい, 好き]                [怒る, 許す, する]    [インドア]
8                              []                          []     [ふつう]
11                             []                          []        []

In [16]:
# Merge the two dataframes
sentences_token_both_df = pd.merge(sentences_token_self_df, sentences_token_target_df, on='MID', suffixes=('_self', '_target'))
sentences_token_both_df.head()

,Adj_self,Verb_self,Noun_self,Adj_target,Verb_target,Noun_target
MID,,,,,,
2,[],[回答],[梨],[],[],[]
5,[],"[見る, 言う]",[文句],"[悪い, ない]","[見かける, 見る, 言う, 見る, 許す, 反応]","[愛想, 文句]"
7,"[直ぐ, 慎重]","[許す, 聞く, 仕事, なる, 落とす, 進める, 飲む, 嫌う]","[人, 道, 休暇, 気, たま, 物, 物事]","[直ぐ, 優しい, 真面目, 勤勉, 大人しい, 好き]","[怒る, 許す, する]",[インドア]
8,[],[],[かし],[],[],[ふつう]
11,"[普通, ない]","[いう, 守る, 排除, する]","[人, 社交, 他者]",[],[],[]

# Indices

## Word Vec Similarity (self vs. target)

### Preparing a word vec model

In [17]:
from gensim.models import Word2Vec
model_path = '../../Materials/word2vec.gensim.model'
model = Word2Vec.load(model_path)

### Vectorilization

In [18]:
# Define a function
def my_vectorization(sentences_token):
    sentences_vector = []
    for sentence in sentences_token:
        vector = []
        for word in sentence:
            try:
                vector.append(model.wv[word])
            except:
                pass
        sentences_vector.append(vector)
    return sentences_vector

In [19]:
# Apply function (self)
word_vec_df_self = pd.DataFrame({
    'Adj_self': my_vectorization(sentences_token_self_df['Adj']),
    'Verb_self': my_vectorization(sentences_token_self_df['Verb']),
    'Noun_self': my_vectorization(sentences_token_self_df['Noun'])
})
word_vec_df_self.set_index(sentences_token_self_df.index, inplace=True)
word_vec_df_self.head()

,Adj_self,Verb_self,Noun_self
MID,,,
2,[],"[[-0.15687115, 0.09542078, -0.2893555, -0.1766...","[[-0.09422035, -0.113751076, 0.032994024, 0.00..."
5,[],"[[-0.031076355, 0.2307243, 0.38670114, 0.07673...","[[0.025084453, -0.057453457, -0.18211138, -0.0..."
7,"[[0.085239545, 0.03890614, 0.006638423, 0.0472...","[[0.066068605, -0.069929995, 0.20459022, 0.021...","[[0.0016509669, 0.024452275, -0.15879686, 0.09..."
8,[],[],"[[-0.06192059, -0.11488108, 0.11417292, -0.089..."
11,"[[0.20946498, 0.14720632, 0.053739548, 0.04463...","[[-0.03642198, -0.07587833, 0.23532403, -0.032...","[[0.0016509669, 0.024452275, -0.15879686, 0.09..."

In [20]:
# Apply function (target)
word_vec_df_target = pd.DataFrame({
    'Adj_target': my_vectorization(sentences_token_target_df['Adj']),
    'Verb_target': my_vectorization(sentences_token_target_df['Verb']),
    'Noun_target': my_vectorization(sentences_token_target_df['Noun'])
})
word_vec_df_target.set_index(sentences_token_target_df.index, inplace=True)
word_vec_df_target.head()

,Adj_target,Verb_target,Noun_target
MID,,,
2,[],[],[]
5,"[[0.2061435, 0.02356317, 0.17509396, -0.006564...","[[0.1032, 0.23523483, 0.3116378, 0.09359262, 0...","[[0.08338137, -0.06351369, 0.041429847, -0.071..."
7,"[[0.085239545, 0.03890614, 0.006638423, 0.0472...","[[0.13081324, -0.088090114, 0.09587991, -0.108...","[[0.16502795, -0.10215739, 0.21511982, -0.0561..."
8,[],[],"[[0.12936483, 0.014520218, -0.005053561, -0.02..."
11,[],[],[]

In [21]:
print(word_vec_df_self.shape, word_vec_df_target.shape)

(479, 3) (479, 3)

### Averaged word vectors

In [22]:
# Define a function for calculating the average of vectors for each cell
def my_average_vector(lst):
    if len(lst) == 0:
        return np.nan
    else:
        return np.mean(lst, axis=0)

In [23]:
avg_vec_self = word_vec_df_self.applymap(my_average_vector)
avg_vec_self.head()

/tmp/ipykernel_19326/554427350.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  avg_vec_self = word_vec_df_self.applymap(my_average_vector)

,Adj_self,Verb_self,Noun_self
MID,,,
2,NaN,"[-0.15687115, 0.09542078, -0.2893555, -0.17661...","[-0.09422035, -0.113751076, 0.032994024, 0.008..."
5,NaN,"[-0.03804296, 0.06086878, 0.33284658, -0.00236...","[0.025084453, -0.057453457, -0.18211138, -0.02..."
7,"[0.08590674, 0.023962865, -0.034617506, 0.0873...","[0.047239266, 0.036973044, 0.23174277, -0.0110...","[0.013854864, 0.0644439, -0.04076126, -0.01054..."
8,NaN,NaN,"[-0.06192059, -0.11488108, 0.11417292, -0.0890..."
11,"[0.04351013, 0.116137885, 0.21674304, 0.083413...","[0.092393845, -0.018872123, 0.21338363, 0.0624...","[0.09440097, 0.04184271, 0.019901117, 0.055466..."

In [24]:
avg_vec_target = word_vec_df_target.applymap(my_average_vector)
avg_vec_target.head()

/tmp/ipykernel_19326/2849788226.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  avg_vec_target = word_vec_df_target.applymap(my_average_vector)

,Adj_target,Verb_target,Noun_target
MID,,,
2,NaN,NaN,NaN
5,"[0.04184939, 0.05431631, 0.27742025, 0.0578135...","[-0.021191051, 0.10711268, 0.23551913, 0.03235...","[0.05423291, -0.060483575, -0.07034077, -0.047..."
7,"[0.2424561, -0.07861761, 0.13673034, 0.0123730...","[0.14786735, -0.07315251, 0.15680052, -0.05466...","[0.16502795, -0.10215739, 0.21511982, -0.05618..."
8,NaN,NaN,"[0.12936483, 0.014520218, -0.005053561, -0.024..."
11,NaN,NaN,NaN

In [25]:
print(avg_vec_self.shape, avg_vec_target.shape)

(479, 3) (479, 3)

### Merge the two dataframes (self and target)

In [26]:
avg_vec_both = avg_vec_self.join(avg_vec_target, how='inner')
avg_vec_both.head()

,Adj_self,Verb_self,Noun_self,Adj_target,Verb_target,Noun_target
MID,,,,,,
2,NaN,"[-0.15687115, 0.09542078, -0.2893555, -0.17661...","[-0.09422035, -0.113751076, 0.032994024, 0.008...",NaN,NaN,NaN
5,NaN,"[-0.03804296, 0.06086878, 0.33284658, -0.00236...","[0.025084453, -0.057453457, -0.18211138, -0.02...","[0.04184939, 0.05431631, 0.27742025, 0.0578135...","[-0.021191051, 0.10711268, 0.23551913, 0.03235...","[0.05423291, -0.060483575, -0.07034077, -0.047..."
7,"[0.08590674, 0.023962865, -0.034617506, 0.0873...","[0.047239266, 0.036973044, 0.23174277, -0.0110...","[0.013854864, 0.0644439, -0.04076126, -0.01054...","[0.2424561, -0.07861761, 0.13673034, 0.0123730...","[0.14786735, -0.07315251, 0.15680052, -0.05466...","[0.16502795, -0.10215739, 0.21511982, -0.05618..."
8,NaN,NaN,"[-0.06192059, -0.11488108, 0.11417292, -0.0890...",NaN,NaN,"[0.12936483, 0.014520218, -0.005053561, -0.024..."
11,"[0.04351013, 0.116137885, 0.21674304, 0.083413...","[0.092393845, -0.018872123, 0.21338363, 0.0624...","[0.09440097, 0.04184271, 0.019901117, 0.055466...",NaN,NaN,NaN

### Word Vec Similarity between Self and Target
cf. https://wakame-msds.com/similarity/
- Euclidean Distance: the curse of dimensionality
- Manhattan Distance: better than the Euclidean
- Cosine Similarity: does not take accoung or the magnitude of each vector (only directions)

In [27]:
# Define a function for calculating the cosine similarity
def calc_cos_sim(v1, v2):
    if np.isnan(v1).any() or np.isnan(v2).any():
        return np.nan
    else:
        return cosine_similarity([v1], [v2])[0][0]

In [28]:
# Define a funcion for calculating the Euclidean distance
def calc_euclidean_dist(v1, v2):
    if np.isnan(v1).any() or np.isnan(v2).any():
        return np.nan
    else:
        return euclidean_distances([v1], [v2])[0][0]

In [29]:
# Define a function for calculating the Manhattan distance
def calc_manhattan_dist(v1, v2):
    if np.isnan(v1).any() or np.isnan(v2).any():
        return np.nan
    else:
        return manhattan_distances([v1], [v2])[0][0]

In [30]:
df_similarity = pd.DataFrame(index=avg_vec_both.index)
df_similarity['Adj_cosine'] = avg_vec_both.apply(lambda x: calc_cos_sim(x['Adj_self'], x['Adj_target']), axis=1)
df_similarity["Adj_euclidean"] = avg_vec_both.apply(lambda x: calc_euclidean_dist(x["Adj_self"], x["Adj_target"]), axis=1)
df_similarity["Adj_manhattan"] = avg_vec_both.apply(lambda x: calc_manhattan_dist(x["Adj_self"], x["Adj_target"]), axis=1)
df_similarity["Verb_cosine"] = avg_vec_both.apply(lambda x: calc_cos_sim(x["Verb_self"], x["Verb_target"]), axis=1)
df_similarity["Verb_euclidean"] = avg_vec_both.apply(lambda x: calc_euclidean_dist(x["Verb_self"], x["Verb_target"]), axis=1)
df_similarity["Verb_manhattan"] = avg_vec_both.apply(lambda x: calc_manhattan_dist(x["Verb_self"], x["Verb_target"]), axis=1)
df_similarity["Noun_cosine"] = avg_vec_both.apply(lambda x: calc_cos_sim(x["Noun_self"], x["Noun_target"]), axis=1)
df_similarity["Noun_euclidean"] = avg_vec_both.apply(lambda x: calc_euclidean_dist(x["Noun_self"], x["Noun_target"]), axis=1)
df_similarity["Noun_manhattan"] = avg_vec_both.apply(lambda x: calc_manhattan_dist(x["Noun_self"], x["Noun_target"]), axis=1)
df_similarity.head()

,Adj_cosine,Adj_euclidean,Adj_manhattan,Verb_cosine,Verb_euclidean,Verb_manhattan,Noun_cosine,Noun_euclidean,Noun_manhattan
MID,,,,,,,,,
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,0.933851,0.344139,1.932724,0.882830,0.469692,2.609289
7,0.489526,0.77925,4.465907,0.826740,0.433577,2.556113,0.035336,1.129285,6.480907
8,NaN,NaN,NaN,NaN,NaN,NaN,0.397660,1.097579,6.200497
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Transformation
High IOS group (5, 6, 7) and Low IOS group (1, 2, and 3)

In [31]:
df = pd.read_csv('./Results/output01_all.csv', header=0, index_col=0)
df.head()

,start,end,rt,self_sex,self_age,residence,participation,IOS_score,target_likedislike,target_sex,...,self_activeness_score,self_sociability_score,target_tolerance_score,target_pleasantness_score,target_responsibility_score,target_carefulness_score,target_activeness_score,target_sociability_score,completion,stratumID
MID,,,,,,,,,,,,,,,,,,,,,
2.0,2024/02/16-12:21:18,2024/02/16-12:24:31,193.0,1.0,45.0,28.0,1.0,5.0,3.0,2.0,...,5.0,2.0,6.0,5.0,1.0,4.0,7.0,6.0,COMP,5.0
5.0,2024/02/16-12:23:21,2024/02/16-12:25:38,137.0,1.0,36.0,28.0,1.0,2.0,4.0,2.0,...,4.0,2.0,5.0,3.0,6.0,2.0,5.0,3.0,COMP,9.0
7.0,2024/02/16-12:20:52,2024/02/16-12:25:45,293.0,1.0,54.0,12.0,1.0,5.0,1.0,2.0,...,5.0,3.0,1.0,7.0,1.0,6.0,6.0,2.0,COMP,5.0
8.0,2024/02/16-12:24:28,2024/02/16-12:26:11,103.0,1.0,36.0,14.0,1.0,1.0,1.0,2.0,...,3.0,3.0,1.0,7.0,1.0,5.0,4.0,7.0,COMP,1.0
11.0,2024/02/16-12:23:46,2024/02/16-12:26:26,160.0,1.0,56.0,13.0,1.0,2.0,1.0,2.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,COMP,2.0

In [32]:
HighIOS_indices = df['IOS_score'] > 4
LowIOS_indices = df['IOS_score'] < 4

In [33]:
# df にIOS_group列を追加
df['IOS_group'] = ['NA'] * len(df)
df.loc[HighIOS_indices, ['IOS_group']] = 'HighIOS'
df.loc[LowIOS_indices, ['IOS_group']] = 'LowIOS'
df.head()

,start,end,rt,self_sex,self_age,residence,participation,IOS_score,target_likedislike,target_sex,...,self_sociability_score,target_tolerance_score,target_pleasantness_score,target_responsibility_score,target_carefulness_score,target_activeness_score,target_sociability_score,completion,stratumID,IOS_group
MID,,,,,,,,,,,,,,,,,,,,,
2.0,2024/02/16-12:21:18,2024/02/16-12:24:31,193.0,1.0,45.0,28.0,1.0,5.0,3.0,2.0,...,2.0,6.0,5.0,1.0,4.0,7.0,6.0,COMP,5.0,HighIOS
5.0,2024/02/16-12:23:21,2024/02/16-12:25:38,137.0,1.0,36.0,28.0,1.0,2.0,4.0,2.0,...,2.0,5.0,3.0,6.0,2.0,5.0,3.0,COMP,9.0,LowIOS
7.0,2024/02/16-12:20:52,2024/02/16-12:25:45,293.0,1.0,54.0,12.0,1.0,5.0,1.0,2.0,...,3.0,1.0,7.0,1.0,6.0,6.0,2.0,COMP,5.0,HighIOS
8.0,2024/02/16-12:24:28,2024/02/16-12:26:11,103.0,1.0,36.0,14.0,1.0,1.0,1.0,2.0,...,3.0,1.0,7.0,1.0,5.0,4.0,7.0,COMP,1.0,LowIOS
11.0,2024/02/16-12:23:46,2024/02/16-12:26:26,160.0,1.0,56.0,13.0,1.0,2.0,1.0,2.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,COMP,2.0,LowIOS

# Output

In [34]:
df.loc[:, ['IOS_score', 'IOS_group']].head()

      IOS_score IOS_group
MID
2.0         5.0   HighIOS
5.0         2.0    LowIOS
7.0         5.0   HighIOS
8.0         1.0    LowIOS
11.0        2.0    LowIOS

In [35]:
# Merge the two dataframes
out_df = pd.merge(df.loc[:, ['IOS_score', 'IOS_group']], df_similarity, on='MID')
out_df.head()

,IOS_score,IOS_group,Adj_cosine,Adj_euclidean,Adj_manhattan,Verb_cosine,Verb_euclidean,Verb_manhattan,Noun_cosine,Noun_euclidean,Noun_manhattan
MID,,,,,,,,,,,
2.0,5.0,HighIOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5.0,2.0,LowIOS,NaN,NaN,NaN,0.933851,0.344139,1.932724,0.882830,0.469692,2.609289
7.0,5.0,HighIOS,0.489526,0.77925,4.465907,0.826740,0.433577,2.556113,0.035336,1.129285,6.480907
8.0,1.0,LowIOS,NaN,NaN,NaN,NaN,NaN,NaN,0.397660,1.097579,6.200497
11.0,2.0,LowIOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
# Save the dataframe
filename = './Results/output02.csv'
out_df.to_csv(filename, index=True)

# Check Distribution

In [38]:
ProfileReport(out_df)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
# 確認用
sentences_token_self_df = pd.DataFrame(sentences_token_self).rename(columns={0: 'MID'})
sentences_token_self_df = sentences_token_self_df.set_index('MID')
sentences_token_self_df.to_csv('./Results/sentences_token_self_df.csv', index=False)

sentences_token_target_df = pd.DataFrame(sentences_token_target).rename(columns={0: 'MID'})
sentences_token_target_df = sentences_token_target_df.set_index('MID')
sentences_token_target_df.to_csv('./Results/sentences_token_target_df.csv', index=False)